---
- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password {{ MYSQL_ROOT_PASSWORD }} | sudo /usr/bin/debconf-set-selections

- name: Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password_again password {{ MYSQL_ROOT_PASSWORD }} | sudo /usr/bin/debconf-set-selections

- name: Install mysql database
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - python-mysqldb
      - mysql-client
      - mysql-server

- name: Copy .my.cnf file with root password credentials
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600
  notify:
   - restart mysql

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_user: "{{ MYSQL_ROOT_USERNAME }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    check_implicit_admin: yes
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

- name: Ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
      - localhost
      - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create Database
  mysql_db:
    login_user: "{{ MYSQL_ROOT_USERNAME }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    name: "{{ mysql.database }}"

- name: Adds required MySQL users
  mysql_user:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.privileges }}"
  with_items:  "{{ mysql.users }}"
  when:  mysql.users is defined