---
- name: Check if writable directories exist
  file:
    dest: "{{ system.root }}/{{ item }}"
    state: directory
    owner: vagrant
    group: nginx
  with_items:
    - backend/runtime
    - backend/web/assets
    - frontend/runtime
    - frontend/web/assets
    - console/runtime

- name: Enable writable directories
  file:
    dest: "{{ system.root }}/{{ item }}"
    mode: 0777
    recurse: yes
  with_items:
    - backend/runtime
    - backend/web/assets
    - frontend/runtime
    - frontend/web/assets
    - console/runtime