---
- name: Update apt
  apt: update_cache=yes

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  apt: pkg={{ item }} state=latest
  with_items: "{{ system.packages }}"
  when: system.packages is defined

- name: Configure the timezone
  template:
    src: "timezone.j2"
    dest: "/etc/timezone"

- name: More Configure the timezone
  file:
    src: "/usr/share/zoneinfo/{{ SYSTEM_TIMEZONE }}"
    dest: "/etc/localtime"
    state: link
    force: yes
    backup: yes

- name: Set default system language pack
  shell: "locale-gen {{ SYSTEM_LOCALE }}"