---
- name: Add repository
  become: true
  apt_repository:
    repo: "{{ PHP_PPA }}"

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PHP
  become: yes
  apt:
    pkg: php7.0
    state: latest

- name: Install PHP Packages
  become: yes
  apt:
    pkg: "php7.0-{{ item }}"
    state: latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart php7-fpm

- include: configure.yml
- include: xdebug.yml