---
- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ PHP_TIMEZONE }}'

- name: disabling opcache cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini
              regexp='opcache.enable_cli='
              line='opcache.enable_cli=0'
