---
- name: Copy Nginx main config
  template:
    src:  "nginx.conf.j2"
    dest: "{{ NGINX_BASE_PATH }}/nginx.conf"
    validate: "nginx -t -c %s"

- name: Create folder conf.d
  file:
    path: "{{ NGINX_CONFIG_PATH }}"
    state: directory

- name: Delete default config
  file:
    path: "{{ NGINX_CONFIG_PATH }}/default.conf"
    state: absent

- name: Make sites available
  template:
    src: "{{item}}.conf.j2"
    dest: "{{ NGINX_CONFIG_PATH }}/{{item}}.conf"
    backup: yes
  with_items: "{{ nginx.sites }}"
  when: nginx.sites is defined
  notify:
      - Enable nginx
      - Restart nginx