---
- name: Ensure apache is absent
  yum:
    name: httpd
    state: absent

- name: Install latest nginx
  yum:
    name: nginx
    state: latest

- name: Ensure service is started and that it always starts on boot
  service:
    name: nginx
    state: started
    enabled: yes